import "./globals.css";
import { Provider } from "@/app/_context/Provider";
import { ModalRoot } from "@/app/_modal/ModalRoot";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <ModalRoot />
          <header className="p-6 font-bold text-lg bg-gray-200">
            Contact Management
          </header>
          {children}
        </Provider>
      </body>
    </html>
  );
}
